require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.3

RSpec/FactoryBot/CreateList:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*